name: do_an_lap_trinh_tren_thiet_bi_di_dong_mychat
description: Ứng dụng Flutter chat và mạng xã hội đơn giản
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1     
  cloud_firestore: ^6.0.3  
  shared_preferences: ^2.5.3
  intl: ^0.19.0 
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
    - assets/avatar.png